# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .aggregate import *
from .asn import *
from .cable import *
from .circuit import *
from .cluster import *
from .contact import *
from .device import *
from .get_asn import *
from .get_asns import *
from .get_cluster import *
from .get_contact import *
from .get_devices import *
from .get_interfaces import *
from .get_location import *
from .get_locations import *
from .get_platform import *
from .get_prefix import *
from .get_prefixes import *
from .get_racks import *
from .get_region import *
from .get_site import *
from .get_tag import *
from .get_tags import *
from .get_tenant import *
from .get_tenants import *
from .get_vlan import *
from .get_vlans import *
from .get_vrf import *
from .get_vrfs import *
from .group import *
from .interface import *
from .location import *
from .manufacturer import *
from .module import *
from .permission import *
from .platform import *
from .prefix import *
from .provider import *
from .rack import *
from .region import *
from .rir import *
from .service import *
from .site import *
from .tag import *
from .tenant import *
from .token import *
from .user import *
from .vlan import *
from .vrf import *
from .webhook import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_netbox.available as __available
    available = __available
    import pulumi_netbox.circuit as __circuit
    circuit = __circuit
    import pulumi_netbox.cluster as __cluster
    cluster = __cluster
    import pulumi_netbox.config as __config
    config = __config
    import pulumi_netbox.contact as __contact
    contact = __contact
    import pulumi_netbox.custom as __custom
    custom = __custom
    import pulumi_netbox.device as __device
    device = __device
    import pulumi_netbox.event as __event
    event = __event
    import pulumi_netbox.interface as __interface
    interface = __interface
    import pulumi_netbox.inventory as __inventory
    inventory = __inventory
    import pulumi_netbox.ip as __ip
    ip = __ip
    import pulumi_netbox.ipam as __ipam
    ipam = __ipam
    import pulumi_netbox.module as __module
    module = __module
    import pulumi_netbox.power as __power
    power = __power
    import pulumi_netbox.primary as __primary
    primary = __primary
    import pulumi_netbox.rack as __rack
    rack = __rack
    import pulumi_netbox.route as __route
    route = __route
    import pulumi_netbox.site as __site
    site = __site
    import pulumi_netbox.tenant as __tenant
    tenant = __tenant
    import pulumi_netbox.virtual as __virtual
    virtual = __virtual
    import pulumi_netbox.vlan as __vlan
    vlan = __vlan
    import pulumi_netbox.vpn as __vpn
    vpn = __vpn
else:
    available = _utilities.lazy_import('pulumi_netbox.available')
    circuit = _utilities.lazy_import('pulumi_netbox.circuit')
    cluster = _utilities.lazy_import('pulumi_netbox.cluster')
    config = _utilities.lazy_import('pulumi_netbox.config')
    contact = _utilities.lazy_import('pulumi_netbox.contact')
    custom = _utilities.lazy_import('pulumi_netbox.custom')
    device = _utilities.lazy_import('pulumi_netbox.device')
    event = _utilities.lazy_import('pulumi_netbox.event')
    interface = _utilities.lazy_import('pulumi_netbox.interface')
    inventory = _utilities.lazy_import('pulumi_netbox.inventory')
    ip = _utilities.lazy_import('pulumi_netbox.ip')
    ipam = _utilities.lazy_import('pulumi_netbox.ipam')
    module = _utilities.lazy_import('pulumi_netbox.module')
    power = _utilities.lazy_import('pulumi_netbox.power')
    primary = _utilities.lazy_import('pulumi_netbox.primary')
    rack = _utilities.lazy_import('pulumi_netbox.rack')
    route = _utilities.lazy_import('pulumi_netbox.route')
    site = _utilities.lazy_import('pulumi_netbox.site')
    tenant = _utilities.lazy_import('pulumi_netbox.tenant')
    virtual = _utilities.lazy_import('pulumi_netbox.virtual')
    vlan = _utilities.lazy_import('pulumi_netbox.vlan')
    vpn = _utilities.lazy_import('pulumi_netbox.vpn')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "netbox",
  "mod": "available/ip/address",
  "fqn": "pulumi_netbox.available.ip",
  "classes": {
   "netbox:available/ip/address:Address": "Address"
  }
 },
 {
  "pkg": "netbox",
  "mod": "available/prefix",
  "fqn": "pulumi_netbox.available",
  "classes": {
   "netbox:available/prefix:Prefix": "Prefix"
  }
 },
 {
  "pkg": "netbox",
  "mod": "circuit/provider",
  "fqn": "pulumi_netbox.circuit",
  "classes": {
   "netbox:circuit/provider:Provider": "Provider"
  }
 },
 {
  "pkg": "netbox",
  "mod": "circuit/termination",
  "fqn": "pulumi_netbox.circuit",
  "classes": {
   "netbox:circuit/termination:Termination": "Termination"
  }
 },
 {
  "pkg": "netbox",
  "mod": "circuit/type",
  "fqn": "pulumi_netbox.circuit",
  "classes": {
   "netbox:circuit/type:Type": "Type"
  }
 },
 {
  "pkg": "netbox",
  "mod": "cluster/group",
  "fqn": "pulumi_netbox.cluster",
  "classes": {
   "netbox:cluster/group:Group": "Group"
  }
 },
 {
  "pkg": "netbox",
  "mod": "cluster/type",
  "fqn": "pulumi_netbox.cluster",
  "classes": {
   "netbox:cluster/type:Type": "Type"
  }
 },
 {
  "pkg": "netbox",
  "mod": "config/context",
  "fqn": "pulumi_netbox.config",
  "classes": {
   "netbox:config/context:Context": "Context"
  }
 },
 {
  "pkg": "netbox",
  "mod": "config/template",
  "fqn": "pulumi_netbox.config",
  "classes": {
   "netbox:config/template:Template": "Template"
  }
 },
 {
  "pkg": "netbox",
  "mod": "contact/assignment",
  "fqn": "pulumi_netbox.contact",
  "classes": {
   "netbox:contact/assignment:Assignment": "Assignment"
  }
 },
 {
  "pkg": "netbox",
  "mod": "contact/group",
  "fqn": "pulumi_netbox.contact",
  "classes": {
   "netbox:contact/group:Group": "Group"
  }
 },
 {
  "pkg": "netbox",
  "mod": "contact/role",
  "fqn": "pulumi_netbox.contact",
  "classes": {
   "netbox:contact/role:Role": "Role"
  }
 },
 {
  "pkg": "netbox",
  "mod": "custom/field",
  "fqn": "pulumi_netbox.custom",
  "classes": {
   "netbox:custom/field:Field": "Field"
  }
 },
 {
  "pkg": "netbox",
  "mod": "custom/field/choice/set",
  "fqn": "pulumi_netbox.custom.field.choice",
  "classes": {
   "netbox:custom/field/choice/set:Set": "Set"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/console/port",
  "fqn": "pulumi_netbox.device.console",
  "classes": {
   "netbox:device/console/port:Port": "Port"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/console/server/port",
  "fqn": "pulumi_netbox.device.console.server",
  "classes": {
   "netbox:device/console/server/port:Port": "Port"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/front/port",
  "fqn": "pulumi_netbox.device.front",
  "classes": {
   "netbox:device/front/port:Port": "Port"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/interface",
  "fqn": "pulumi_netbox.device",
  "classes": {
   "netbox:device/interface:Interface": "Interface"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/module/bay",
  "fqn": "pulumi_netbox.device.module",
  "classes": {
   "netbox:device/module/bay:Bay": "Bay"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/power/outlet",
  "fqn": "pulumi_netbox.device.power",
  "classes": {
   "netbox:device/power/outlet:Outlet": "Outlet"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/power/port",
  "fqn": "pulumi_netbox.device.power",
  "classes": {
   "netbox:device/power/port:Port": "Port"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/primary/ip",
  "fqn": "pulumi_netbox.device.primary",
  "classes": {
   "netbox:device/primary/ip:Ip": "Ip"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/rear/port",
  "fqn": "pulumi_netbox.device.rear",
  "classes": {
   "netbox:device/rear/port:Port": "Port"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/role",
  "fqn": "pulumi_netbox.device",
  "classes": {
   "netbox:device/role:Role": "Role"
  }
 },
 {
  "pkg": "netbox",
  "mod": "device/type",
  "fqn": "pulumi_netbox.device",
  "classes": {
   "netbox:device/type:Type": "Type"
  }
 },
 {
  "pkg": "netbox",
  "mod": "event/rule",
  "fqn": "pulumi_netbox.event",
  "classes": {
   "netbox:event/rule:Rule": "Rule"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/aggregate",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/aggregate:Aggregate": "Aggregate"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/asn",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/asn:Asn": "Asn"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/cable",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/cable:Cable": "Cable"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/circuit",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/circuit:Circuit": "Circuit"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/cluster",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/cluster:Cluster": "Cluster"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/contact",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/contact:Contact": "Contact"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/device",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/device:Device": "Device"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/group",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/group:Group": "Group"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/interface",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/interface:Interface": "Interface"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/location",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/location:Location": "Location"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/manufacturer",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/manufacturer:Manufacturer": "Manufacturer"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/module",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/module:Module": "Module"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/permission",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/permission:Permission": "Permission"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/platform",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/platform:Platform": "Platform"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/prefix",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/prefix:Prefix": "Prefix"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/rack",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/rack:Rack": "Rack"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/region",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/region:Region": "Region"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/rir",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/rir:Rir": "Rir"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/service",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/service:Service": "Service"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/site",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/site:Site": "Site"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/tag",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/tag:Tag": "Tag"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/tenant",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/tenant:Tenant": "Tenant"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/token",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/token:Token": "Token"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/user",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/user:User": "User"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/vlan",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/vlan:Vlan": "Vlan"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/vrf",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/vrf:Vrf": "Vrf"
  }
 },
 {
  "pkg": "netbox",
  "mod": "index/webhook",
  "fqn": "pulumi_netbox",
  "classes": {
   "netbox:index/webhook:Webhook": "Webhook"
  }
 },
 {
  "pkg": "netbox",
  "mod": "interface/template",
  "fqn": "pulumi_netbox.interface",
  "classes": {
   "netbox:interface/template:Template": "Template"
  }
 },
 {
  "pkg": "netbox",
  "mod": "inventory/item",
  "fqn": "pulumi_netbox.inventory",
  "classes": {
   "netbox:inventory/item:Item": "Item"
  }
 },
 {
  "pkg": "netbox",
  "mod": "inventory/item/role",
  "fqn": "pulumi_netbox.inventory.item",
  "classes": {
   "netbox:inventory/item/role:Role": "Role"
  }
 },
 {
  "pkg": "netbox",
  "mod": "ip/address",
  "fqn": "pulumi_netbox.ip",
  "classes": {
   "netbox:ip/address:Address": "Address"
  }
 },
 {
  "pkg": "netbox",
  "mod": "ip/range",
  "fqn": "pulumi_netbox.ip",
  "classes": {
   "netbox:ip/range:Range": "Range"
  }
 },
 {
  "pkg": "netbox",
  "mod": "ipam/role",
  "fqn": "pulumi_netbox.ipam",
  "classes": {
   "netbox:ipam/role:Role": "Role"
  }
 },
 {
  "pkg": "netbox",
  "mod": "module/type",
  "fqn": "pulumi_netbox.module",
  "classes": {
   "netbox:module/type:Type": "Type"
  }
 },
 {
  "pkg": "netbox",
  "mod": "power/feed",
  "fqn": "pulumi_netbox.power",
  "classes": {
   "netbox:power/feed:Feed": "Feed"
  }
 },
 {
  "pkg": "netbox",
  "mod": "power/panel",
  "fqn": "pulumi_netbox.power",
  "classes": {
   "netbox:power/panel:Panel": "Panel"
  }
 },
 {
  "pkg": "netbox",
  "mod": "primary/ip",
  "fqn": "pulumi_netbox.primary",
  "classes": {
   "netbox:primary/ip:Ip": "Ip"
  }
 },
 {
  "pkg": "netbox",
  "mod": "rack/reservation",
  "fqn": "pulumi_netbox.rack",
  "classes": {
   "netbox:rack/reservation:Reservation": "Reservation"
  }
 },
 {
  "pkg": "netbox",
  "mod": "rack/role",
  "fqn": "pulumi_netbox.rack",
  "classes": {
   "netbox:rack/role:Role": "Role"
  }
 },
 {
  "pkg": "netbox",
  "mod": "route/target",
  "fqn": "pulumi_netbox.route",
  "classes": {
   "netbox:route/target:Target": "Target"
  }
 },
 {
  "pkg": "netbox",
  "mod": "site/group",
  "fqn": "pulumi_netbox.site",
  "classes": {
   "netbox:site/group:Group": "Group"
  }
 },
 {
  "pkg": "netbox",
  "mod": "tenant/group",
  "fqn": "pulumi_netbox.tenant",
  "classes": {
   "netbox:tenant/group:Group": "Group"
  }
 },
 {
  "pkg": "netbox",
  "mod": "virtual/chassis",
  "fqn": "pulumi_netbox.virtual",
  "classes": {
   "netbox:virtual/chassis:Chassis": "Chassis"
  }
 },
 {
  "pkg": "netbox",
  "mod": "virtual/disk",
  "fqn": "pulumi_netbox.virtual",
  "classes": {
   "netbox:virtual/disk:Disk": "Disk"
  }
 },
 {
  "pkg": "netbox",
  "mod": "virtual/machine",
  "fqn": "pulumi_netbox.virtual",
  "classes": {
   "netbox:virtual/machine:Machine": "Machine"
  }
 },
 {
  "pkg": "netbox",
  "mod": "vlan/group",
  "fqn": "pulumi_netbox.vlan",
  "classes": {
   "netbox:vlan/group:Group": "Group"
  }
 },
 {
  "pkg": "netbox",
  "mod": "vpn/tunnel",
  "fqn": "pulumi_netbox.vpn",
  "classes": {
   "netbox:vpn/tunnel:Tunnel": "Tunnel"
  }
 },
 {
  "pkg": "netbox",
  "mod": "vpn/tunnel/group",
  "fqn": "pulumi_netbox.vpn.tunnel",
  "classes": {
   "netbox:vpn/tunnel/group:Group": "Group"
  }
 },
 {
  "pkg": "netbox",
  "mod": "vpn/tunnel/termination",
  "fqn": "pulumi_netbox.vpn.tunnel",
  "classes": {
   "netbox:vpn/tunnel/termination:Termination": "Termination"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "netbox",
  "token": "pulumi:providers:netbox",
  "fqn": "pulumi_netbox",
  "class": "Provider"
 }
]
"""
)
