# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from .. import _utilities
import typing
# Export this package's modules as members:
from .get_interfaces import *
from .get_role import *
from .get_type import *
from .interface import *
from .role import *
from .type import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_netbox.device.console as __console
    console = __console
    import pulumi_netbox.device.front as __front
    front = __front
    import pulumi_netbox.device.module as __module
    module = __module
    import pulumi_netbox.device.power as __power
    power = __power
    import pulumi_netbox.device.primary as __primary
    primary = __primary
    import pulumi_netbox.device.rear as __rear
    rear = __rear
else:
    console = _utilities.lazy_import('pulumi_netbox.device.console')
    front = _utilities.lazy_import('pulumi_netbox.device.front')
    module = _utilities.lazy_import('pulumi_netbox.device.module')
    power = _utilities.lazy_import('pulumi_netbox.device.power')
    primary = _utilities.lazy_import('pulumi_netbox.device.primary')
    rear = _utilities.lazy_import('pulumi_netbox.device.rear')

