# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from ... import _utilities
import typing

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_netbox.custom.field.choice as __choice
    choice = __choice
else:
    choice = _utilities.lazy_import('pulumi_netbox.custom.field.choice')

